# Generated by Django 4.2.18 on 2026-06-02 01:20

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFE_SAIDA', 'NF-e Saída'), ('NFE_ENTRADA', 'NF-e Entrada'), ('NFCE', 'NFC-e'), ('NFSE', 'NFS-e'), ('CTE', 'CT-e'), ('MDFE', 'MDF-e')], max_length=20)),
                ('chave_acesso', models.CharField(max_length=80, unique=True)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('natureza', models.CharField(blank=True, max_length=120)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('situacao', models.CharField(choices=[('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente'), ('ERRO', 'Erro')], default='CONCLUIDO', max_length=20)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=14)),
                ('destinatario_cnpj', models.CharField(blank=True, max_length=14)),
                ('mes', models.IntegerField(default=1)),
                ('ano', models.IntegerField(default=2026)),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to=documentos.models.caminho_xml)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Documento fiscal',
                'verbose_name_plural': 'Documentos fiscais',
                'ordering': ['-data_emissao', '-id'],
                'indexes': [models.Index(fields=['empresa', 'ano', 'mes'], name='documentos__empresa_84f804_idx'), models.Index(fields=['tipo_documento'], name='documentos__tipo_do_1d0d20_idx'), models.Index(fields=['chave_acesso'], name='documentos__chave_a_6b2346_idx')],
            },
        ),
    ]
