# Generated by Django 4.2.18 on 2026-06-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_limpar_xml_nuvem_empresa_meses_retencao_xml'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofiscal',
            options={'ordering': ['-data_emissao', '-numero'], 'verbose_name': 'Documento fiscal', 'verbose_name_plural': 'Documentos fiscais'},
        ),
        migrations.RemoveIndex(
            model_name='documentofiscal',
            name='documentos__empresa_84f804_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentofiscal',
            name='documentos__tipo_do_1d0d20_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentofiscal',
            name='documentos__chave_a_6b2346_idx',
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='xml_conteudo',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo XML'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='chave_acesso',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='natureza',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='serie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='situacao',
            field=models.CharField(choices=[('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('INUTILIZADO', 'Inutilizado'), ('PENDENTE', 'Pendente')], default='CONCLUIDO', max_length=20),
        ),
    ]
