# Generated by Django 4.2.18 on 2026-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limpar_xml_nuvem',
            field=models.BooleanField(default=True, verbose_name='Apagar XML antigo da nuvem'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meses_retencao_xml',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 meses'), (3, '3 meses')], default=3, verbose_name='Manter XML na nuvem por'),
        ),
    ]
