# Generated by Django 4.2.18 on 2026-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_limpar_xml_nuvem_empresa_meses_retencao_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ultima_limpeza_xml',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última limpeza automática de XML'),
        ),
    ]
